# Generated by Django 3.0.5 on 2020-04-19 14:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('hint', models.TextField()),
                ('type', models.TextField(max_length=50)),
                ('test_id', models.IntegerField()),
                ('category', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Stimulus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('filename', models.TextField(blank=True, null=True)),
                ('order', models.PositiveSmallIntegerField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stimulus', to='exceltest.Question')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_1_text', models.TextField(blank=True, null=True)),
                ('column_2_text', models.TextField(blank=True, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('filename', models.TextField(blank=True, null=True)),
                ('order', models.PositiveSmallIntegerField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='exceltest.Question')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.TextField(blank=True, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('filename', models.TextField(blank=True, null=True)),
                ('order', models.PositiveSmallIntegerField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('correct', models.BooleanField(default=False)),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='exceltest.Question')),
            ],
        ),
    ]
